apiVersion: v1
kind: ConfigMap
metadata:
  name: angie-cm
  namespace: homework
data:
  default: |
    server {
      listen       80;
      server_name  localhost;
      location / {
        root   /homework;
        index  index.html index.htm;
      }
    }
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angie-deployment
  namespace: homework
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: angie
  template:
    metadata:
      labels:
        app: angie
    spec:
      containers:
      - name: angie
        image: docker.angie.software/angie:latest
        livenessProbe:
          exec:
            command:
            - cat
            - /homework/index.html
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","rm /homework/index.html"]
        ports:
        - containerPort: 80
          # hostPort: 8000
        volumeMounts:
        - name: workdir
          mountPath: "/homework"
        - name: config
          mountPath: "/etc/angie/http.d/"
      initContainers:
      - name: install
        image: busybox
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - http://info.cern.ch
        volumeMounts:
        - name: workdir
          mountPath: "/init"
      nodeSelector:
        homework: "true"
      volumes:
      - name: workdir
        emptyDir: {}
      - name: config
        configMap:
          name: angie-cm
          items:
          - key: "default"
            path: "default.conf"
