apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: homework
spec:
  containers:
  - name: nginx
    image: docker.angie.software/angie:latest
      #image: nginx:1.29.1
    ports:
    - containerPort: 80
      hostPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: "/homework"
# These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/init"
  volumes:
  - name: workdir
    emptyDir: {}        
